# Generated by Django 3.2.4 on 2021-06-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pword', models.CharField(max_length=200)),
                ('workload', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('state', models.CharField(max_length=200)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_master_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_master_app.user')),
            ],
        ),
    ]
