# Generated by Django 3.2.4 on 2021-06-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='user_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='task_master_app.user'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='user_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='task_master_app.user'),
        ),
    ]
