# Generated by Django 3.2.4 on 2021-06-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0002_auto_20210623_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
    ]
