# Generated by Django 3.2.4 on 2021-06-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0003_rename_connections_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user_receiver',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='user_sender',
        ),
        migrations.AddField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='task_master_app.user'),
        ),
        migrations.AddField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='task_master_app.user'),
        ),
    ]
