# Generated by Django 3.2.4 on 2021-06-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0004_auto_20210627_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='task_master_app.user'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='task_master_app.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(default='Not Started', max_length=200),
        ),
    ]
