# Generated by Django 3.2.4 on 2021-06-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0007_auto_20210630_1730'),
        ('task_master_app', '0007_auto_20210630_2011'),
    ]

    operations = [
    ]
