# Generated by Django 3.2.4 on 2021-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_master_app', '0009_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
